services:
  frontend:
    #image: kind-connect-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: kind-connect-prod

    restart: unless-stopped

    ports:
      - 80:80

  